---
title: "ISLR Chapter5 Resampling Methods"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Conceptual Excercises

1. Using basic statistical properties of the variance, as well as single variable calculus, derive (5.6)

2. Suppose that we obtain a bootstrap sample from a set of *n* observations
  a) What is the probability that the first bootstrap observation is *not* the *j*th observation from the original sample? 
    
1 - 1/n 
    
  b) What is the probability the second bootstrap observation is *not* the *j*th observation from the original sample?  
    
probability is 1/n  as bootstrapping samples with replacement 
    
  c) Argue that the *j*th observation is *not* in the bootstrap sample 
  
As bootstrapping samples with replacement each probability of *j*th not being in the bootstrapping sample is independent 
  
(1 - 1/n)...(1 - 1/n) = (1 - 1/n)^n^
  
  d) When *n* = 5, what is the probability that the *j*th observation
  
n = 5
1 - (1 - 1/5)^5^ =  0.67232

  e) When n = 100, what is the probability that the *j*th observation is in the bootstrap sample?
  
n = 100
1 - (1 - 1/100)^100 = 0.6339677
  
  f) When n = 10,000, what is probability that the *j*th observation is in the bootstrap sample

n = 10000
1 - (1 - 1/10000)^10000 = 0.632139

  g) Create a plot that displays , for each integer value of *n* from 1 to 100,000, the probability that the *j*th observation is in the bootstrap sample. Commrn on what you observe?

  h) We will now investigate numerically the probability that a bootstrap sample of size = 100 contains the *j*th observation. Here *j* 

